// @ts-nocheck
// ANNALES DU CONCOURS D'INTERNAT EN PHARMACIE — sujets officiels.
//
// PROVENANCE. Ce sont les sujets OFFICIELS du concours, organisé par le Centre National de
// Gestion (CNG). Ils sont reproduits ici À DES FINS DE RÉVISION, avec leur provenance indiquée.
// Ils NE relèvent PAS de la licence CC BY-NC-SA du reste du site : ce sont des documents
// tiers, propriété de leur émetteur. Source de référence : https://www.cng.sante.fr/annales
// (grilles de réponses recoupées via medshake.net).
//
// Chaque item est rattaché au(x) chapitre(s) du cours qu'il recoupe (chapterSlugs), pour que
// chaque chapitre puisse renvoyer vers les annales portant sur son thème.
//
// Schéma d'un item :
//   { n, type:'qcm'|'dossier'|'exercice', prompt, options?:[{l,t}], answer?, correction?,
//     chapterSlugs:[...], programItems:[...] }

/** @typedef {{n:number, type:string, prompt:string, options?:{l:string,t:string}[], answer?:string, correction?:string, chapterSlugs:string[], programItems:string[]}} AnnaleItem */

export const annalesSessions = [
  {
    key: '2023',
    label: 'Décembre 2023',
    source: 'Concours national d\'internat en pharmacie — session de décembre 2023 (CNG).',
    items: [
    { n: 1, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la gentamicine, laquelle est fausse ?', options: [{ l: 'A', t: 'Elle peut être à l\'origine d\'une néphrotoxicité' }, { l: 'B', t: 'Elle est bactéricide sur les bacilles Gram (-) aérobies' }, { l: 'C', t: 'Elle est éliminée sous forme active par voie rénale' }, { l: 'D', t: 'Elle peut être à l\'origine d\'une ototoxicité' }, { l: 'E', t: 'Elle agit par fixation sur la sous-unité 50S du ribosome' }], answer: 'E', chapterSlugs: ["v-27-aminosides"], programItems: ["V-27"] },
    { n: 2, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'acidose lactique, quelle est celle qui est fausse ?', options: [{ l: 'A', t: 'Elle s\'accompagne d\'une augmentation du trou anionique plasmatique' }, { l: 'B', t: 'Elle peut survenir chez le diabétique de type 2 traité par la metformine' }, { l: 'C', t: 'Elle s\'accompagne d\'une hypokaliémie' }, { l: 'D', t: 'Elle peut entraîner un coma' }, { l: 'E', t: 'Elle s\'accompagne d\'une hyperventilation' }], answer: 'C', chapterSlugs: ["iv-42-troubles-acidobasiques"], programItems: ["IV-42"] },
    { n: 3, type: 'qcm', prompt: 'Chez un patient présentant une anémie mégalocytaire, quel est l\'examen qui permet d\'affirmer le diagnostic de maladie de Biermer ?', options: [{ l: 'A', t: 'Dosage plasmatique de la vitamine B12' }, { l: 'B', t: 'Myélogramme' }, { l: 'C', t: 'Recherche d\'anticorps anti-facteur intrinsèque' }, { l: 'D', t: 'Mesure du pH gastrique' }, { l: 'E', t: 'Dosage de l\'acide méthylmalonique urinaire' }], answer: 'C', chapterSlugs: ["hemato-anemies"], programItems: ["IV-22"] },
    { n: 4, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le virus de l\'hépatite C, une seule est fausse. Laquelle ?', options: [{ l: 'A', t: 'Il appartient à la famille des Flaviviridae' }, { l: 'B', t: 'Le diagnostic d\'hépatite C chronique est sérologique' }, { l: 'C', t: 'Sa réplication est freinée par des inhibiteurs de la polymérase' }, { l: 'D', t: 'Le virion est enveloppé' }, { l: 'E', t: 'Sa transmission est parentérale' }], answer: 'B', chapterSlugs: ["v-53-nutrition-parenterale"], programItems: ["V-53"] },
    { n: 5, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la tuberculose pulmonaire, laquelle est exacte ?', options: [{ l: 'A', t: 'L\'agent étiologique peut être cultivé sur gélose enrichie de sang' }, { l: 'B', t: 'La rifampicine en monothérapie constitue l\'antibiothérapie de 1ère intention' }, { l: 'C', t: 'Il n\'existe pas de prophylaxie vaccinale' }, { l: 'D', t: 'L\'infection peut être d\'origine nosocomiale' }, { l: 'E', t: 'L\'agent étiologique survit dans l\'environnement' }], answer: 'D', chapterSlugs: ["iii-9-risque-iatrogene-nosocomial"], programItems: ["III-9"] },
    { n: 6, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le mode de transmission des virus de l\'immunodéficience humaine (VIH), laquelle est fausse ?', options: [{ l: 'A', t: 'Transmission par transfusion sanguine' }, { l: 'B', t: 'Transmission par usage de drogues par voie intraveineuse' }, { l: 'C', t: 'Transmission par ingestion d\'eau contaminée' }, { l: 'D', t: 'Transmission par l\'allaitement maternel' }, { l: 'E', t: 'Transmission sexuelle' }], answer: 'C', chapterSlugs: ["ii-3-genetique-maladies-monogeniques"], programItems: ["II-3"] },
    { n: 7, type: 'qcm', prompt: 'Parmi les substances actives suivantes utilisées dans le traitement de la maladie de Parkinson, laquelle ne possède pas de propriétés inhibitrices enzymatiques ?', options: [{ l: 'A', t: 'Sélégiline' }, { l: 'B', t: 'Ropinirole' }, { l: 'C', t: 'Entacapone' }, { l: 'D', t: 'Carbidopa' }, { l: 'E', t: 'Bensérazide' }], answer: 'B', chapterSlugs: ["v-7-neurologie"], programItems: ["V-7"] },
    { n: 8, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant Escherichia coli, laquelle est fausse ?', options: [{ l: 'A', t: 'C\'est l\'espèce bactérienne la plus fréquemment responsable de cystites' }, { l: 'B', t: 'Les souches entérotoxinogènes sont responsables de diarrhées du voyageur' }, { l: 'C', t: 'Les souches productrices de pénicillinase sont sensibles au céfotaxime' }, { l: 'D', t: 'La résistance à la ciprofloxacine peut être due à une mutation du gène de l\'ADN-gyrase' }, { l: 'E', t: 'Les pyélonéphrites peuvent être traitées par la vancomycine' }], answer: 'E', chapterSlugs: ["v-59-cellules-souches-hematopoietiques"], programItems: ["V-59"] },
    { n: 9, type: 'qcm', prompt: 'Parmi les propositions suivantes, indiquer celle qui est exacte. Un sujet appartenant au groupe sanguin AB présente', options: [{ l: 'A', t: 'Aucun anticorps naturel régulier' }, { l: 'B', t: 'Des anticorps naturels anti-B' }, { l: 'C', t: 'Des anticorps naturels anti-H' }, { l: 'D', t: 'Des anticorps naturels anti-A et anti-B' }, { l: 'E', t: 'Des anticorps naturels anti-A' }], answer: 'A', chapterSlugs: ["iv-33-maladies-auto-immunes"], programItems: ["IV-33"] },
    { n: 11, type: 'qcm', prompt: 'Parmi les méthodes suivantes, lesquelles permettent le dosage du sodium dans les liquides biologiques ?', options: [{ l: 'A', t: 'Potentiométrie' }, { l: 'B', t: 'Spectrophotométrie UV-visible' }, { l: 'C', t: 'Spectrophotométrie d\'émission atomique' }, { l: 'D', t: 'Ampérométrie' }, { l: 'E', t: 'Complexométrie' }], answer: 'AC', chapterSlugs: ["i-3-spectrophotometrie-uv-visible"], programItems: ["I-3"] },
    { n: 12, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les antigènes T indépendants, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Ce sont des macromolécules à épitopes répétitifs' }, { l: 'B', t: 'Ils induisent essentiellement la production d\'IgE' }, { l: 'C', t: 'Ils sont incapables de générer une mémoire immunitaire' }, { l: 'D', t: 'Ils induisent une maturation de la réponse immunitaire avec production d\'Ig d\'affinité de plus en plus élevée' }, { l: 'E', t: 'Ils entrent dans la composition des vaccins à antigènes conjugués' }], answer: 'ACE', chapterSlugs: ["ii-30-immunologie-organes-cellules-immunitaires"], programItems: ["II-30"] },
    { n: 13, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'insulinothérapie, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'L\'insuline peut provoquer une hypokaliémie' }, { l: 'B', t: 'Les seringues à insuline sont graduées en unités de telle sorte que 100 UI = 1 mL' }, { l: 'C', t: 'Les lipodystrophies sont un effet indésirable de l\'insuline' }, { l: 'D', t: 'Les insulines NPH sont parfois présentées en association avec une insuline rapide en solution' }, { l: 'E', t: 'L\'insuline glulisine est une insuline lente' }], answer: 'ABCD', chapterSlugs: ["v-22-antidiabetiques"], programItems: ["V-22"] },
    { n: 14, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les comprimés, lesquelles sont exactes ?', options: [{ l: 'A', t: 'Le lactose est un des diluants les plus employés' }, { l: 'B', t: 'L\'amidon peut être utilisé comme agent de désagrégation' }, { l: 'C', t: 'Le stéarate de magnésium est un agent d\'enrobage' }, { l: 'D', t: 'Au contact de l\'eau, le mélange acide citrique - bicarbonate de sodium permet la désagrégation' }, { l: 'E', t: 'La silice colloïdale est un liant' }], answer: 'ABD', chapterSlugs: ["i-12-acide-base-ph-tampons"], programItems: ["I-12"] },
    { n: 15, type: 'qcm', prompt: 'Parmi les propositions suivantes, laquelle (lesquelles) est (sont) exacte(s) ? La conjugaison hépatique de la bilirubine', options: [{ l: 'A', t: 'S\'effectue dans les cellules de Küppfer' }, { l: 'B', t: 'Est catalysée par l\'uridine diphosphoglucuronosyltransférase (UDPGT)' }, { l: 'C', t: 'Est inhibée par le phénobarbital' }, { l: 'D', t: 'Conduit à la formation d\'un composé hydrosoluble' }, { l: 'E', t: 'Permet son élimination par transport actif dans la bile' }], answer: 'BDE', chapterSlugs: ["iv-44-cholestase-cytolyse"], programItems: ["IV-44"] },
    { n: 16, type: 'qcm', prompt: 'Parmi les composés suivants, quel(s) est (sont) celui (ceux) dont la concentration plasmatique augmente après 48 heures de jeûne chez un sujet au repos ?', options: [{ l: 'A', t: 'Les chylomicrons' }, { l: 'B', t: 'Les corps cétoniques' }, { l: 'C', t: 'Le lactate' }, { l: 'D', t: 'Le glucose' }, { l: 'E', t: 'Les acides gras non estérifiés' }], answer: 'BE', chapterSlugs: ["ii-13-biochimie-cetogenese"], programItems: ["II-13"] },
    { n: 17, type: 'qcm', prompt: 'Parmi les protéines suivantes, quelle(s) est (sont) celle(s) qui peut (peuvent) être produite(s) par Staphylococcus aureus ?', options: [{ l: 'A', t: 'Une coagulase liée' }, { l: 'B', t: 'Une vérotoxine' }, { l: 'C', t: 'Une endotoxine' }, { l: 'D', t: 'Une pénicillinase' }, { l: 'E', t: 'Une désoxyribonucléase' }], answer: 'ADE', chapterSlugs: ["ii-1-genetique-genome-humain"], programItems: ["II-1"] },
    { n: 18, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les formes galéniques orales, laquelle (lesquelles) permet (permettent) une libération prolongée du principe actif ?', options: [{ l: 'A', t: 'Comprimés osmotiques' }, { l: 'B', t: 'Matrices érodables' }, { l: 'C', t: 'Matrices hydrophiles' }, { l: 'D', t: 'Capsules molles' }, { l: 'E', t: 'Matrices inertes' }], answer: 'ABCE', chapterSlugs: ["v-52-formes-liberation-distribution-modifiees"], programItems: ["V-52"] },
    { n: 19, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les antibiotiques de la famille des bêta-lactamines, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Ils agissent par perturbation de la synthèse de la paroi bactérienne' }, { l: 'B', t: 'Ils agissent en se fixant au niveau des ribosomes bactériens' }, { l: 'C', t: 'Ils ne sont actifs que sur les bactéries à Gram négatif' }, { l: 'D', t: 'Ils peuvent être inactivés par des enzymes bactériennes appelées transpeptidases' }, { l: 'E', t: 'Ils sont susceptibles de provoquer des manifestations allergiques' }], answer: 'AE', chapterSlugs: ["v-24-beta-lactames"], programItems: ["V-24"] },
    { n: 20, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la syphilis, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Cette infection peut avoir une localisation neuroméningée' }, { l: 'B', t: 'L\'agent causal est isolé sur milieu de culture enrichi en facteurs de croissance' }, { l: 'C', t: 'Il existe une prophylaxie vaccinale' }, { l: 'D', t: 'C\'est une infection transmissible de la mère à l\'enfant' }, { l: 'E', t: 'La benzylpénicilline constitue un traitement de choix' }], answer: 'ADE', chapterSlugs: ["i-13-protometrie-milieu-non-aqueux"], programItems: ["I-13"] },
    { n: 21, type: 'qcm', prompt: 'Parmi les médicaments cytotoxiques suivants, quels sont ceux qui sont des antimétabolites ?', options: [{ l: 'A', t: 'Paclitaxel' }, { l: 'B', t: 'Fluorouracile' }, { l: 'C', t: 'Mercaptopurine' }, { l: 'D', t: 'Etoposide' }, { l: 'E', t: 'Cyclophosphamide' }], answer: 'BC', chapterSlugs: ["v-42-anticancereux"], programItems: ["V-42"] },
    { n: 22, type: 'qcm', prompt: 'Parmi les propositions suivantes, laquelle (lesquelles) est (sont) exacte(s) ? La paroi du tube digestif contient', options: [{ l: 'A', t: 'Des fibres musculaires striées' }, { l: 'B', t: 'Des terminaisons du système nerveux autonome' }, { l: 'C', t: 'Des cellules exocrines' }, { l: 'D', t: 'Des cellules endocrines' }, { l: 'E', t: 'Des ilôts lymphoïdes' }], answer: 'ABCDE', chapterSlugs: ["v-59-cellules-souches-hematopoietiques"], programItems: ["V-59"] },
    { n: 23, type: 'qcm', prompt: 'Parmi les principes actifs médicamenteux suivants, quel(s) est (sont) celui (ceux) qui a (ont) une structure stéroïdienne ?', options: [{ l: 'A', t: 'Amiloride' }, { l: 'B', t: 'Spironolactone' }, { l: 'C', t: 'Digoxine' }, { l: 'D', t: 'Dexaméthasone' }, { l: 'E', t: 'Méthotrexate' }], answer: 'BCD', chapterSlugs: ["v-2-facteurs-sort-principes-actifs"], programItems: ["V-2"] },
    { n: 24, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le mode d\'action des antibiotiques sur les bactéries, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Les aminosides interagissent avec le ribosome' }, { l: 'B', t: 'Les glycopeptides se fixent sur l\'ADN gyrase' }, { l: 'C', t: 'La rifamycine se fixe sur l\'ARN polymérase' }, { l: 'D', t: 'Les cyclines bloquent la synthèse protéique' }, { l: 'E', t: 'Les macrolides bloquent la synthèse du peptidoglycane' }], answer: 'ACD', chapterSlugs: ["v-25-macrolides"], programItems: ["V-25"] },
    { n: 25, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les cellules Natural Killer (NK), laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Elles expriment un récepteur de reconnaissance de l\'antigène' }, { l: 'B', t: 'Elles ont une morphologie de grands lymphocytes granuleux' }, { l: 'C', t: 'Elles expriment le CD56' }, { l: 'D', t: 'Elles ont une activité phagocytaire médiée par le récepteur de Fc gamma R III (ou CD16)' }, { l: 'E', t: 'Elles expriment des récepteurs pour les molécules du CMH de classe I' }], answer: 'BCE', chapterSlugs: ["ii-29-immunologie-cmh-presentation-antigene"], programItems: ["II-29"] },
    { n: 26, type: 'qcm', prompt: 'Quelle(s) est (sont) la (les) proposition(s) exacte(s) ? Une hypercalcémie associée à une concentration d\'hormone parathyroïdienne (1-84) diminuée se rencontre au cours', options: [{ l: 'A', t: 'D\'une insuffisance rénale chronique' }, { l: 'B', t: 'D\'un rachitisme' }, { l: 'C', t: 'D\'une pseudo-hyperparathyroïdie' }, { l: 'D', t: 'D\'une intoxication par la vitamine D' }, { l: 'E', t: 'D\'une hyperthyroïdie primitive' }], answer: 'CD', chapterSlugs: ["iv-46-insuffisance-renale"], programItems: ["IV-46"] },
    { n: 27, type: 'qcm', prompt: 'Quelle(s) est (sont) la (les) circonstance(s) d\'apparition d\'une polyglobulie ?', options: [{ l: 'A', t: 'Insuffisance respiratoire chronique' }, { l: 'B', t: 'Insuffisance rénale chronique' }, { l: 'C', t: 'Séjour prolongé en haute altitude' }, { l: 'D', t: 'Alcoolisme chronique' }, { l: 'E', t: 'Maladie de Vaquez' }], answer: 'ACE', chapterSlugs: ["iv-47-sca-insuffisance-cardiaque"], programItems: ["IV-47"] },
    { n: 28, type: 'qcm', prompt: 'Quel(s) est (sont) le(s) signe(s) biologique(s) fréquemment rencontré(s) lors d\'une cirrhose décompensée ?', options: [{ l: 'A', t: 'Augmentation de la transferrinémie' }, { l: 'B', t: 'Augmentation de l\'albuminémie' }, { l: 'C', t: 'Formation de liquide d\'ascite' }, { l: 'D', t: 'Diminution de l\'activité du complexe prothrombinique' }, { l: 'E', t: 'Diminution de l\'urée plasmatique' }], answer: 'CDE', chapterSlugs: ["i-1-extraction-separation"], programItems: ["I-1"] },
    { n: 29, type: 'qcm', prompt: 'Quelle(s) est (sont) la (les) proposition(s) exacte(s) ? Au cours du syndrome néphrotique, est observée', options: [{ l: 'A', t: 'Une diminution de l\'albuminémie' }, { l: 'B', t: 'Une augmentation de la pression oncotique plasmatique' }, { l: 'C', t: 'La présence d\'œdèmes' }, { l: 'D', t: 'Une diminution de la synthèse hépatique des lipoprotéines' }, { l: 'E', t: 'Une protéinurie supérieure à 3 g / 24 h' }], answer: 'ACE', chapterSlugs: ["iv-46-insuffisance-renale"], programItems: ["IV-46"] },
    { n: 30, type: 'qcm', prompt: 'Parmi les propositions suivantes, quelle(s) est (sont) la (les) contre-indication(s) à l\'administration d\'une Héparine de Bas Poids Moléculaire (HBPM) pour le traitement d\'un épisode aigu de thrombose veineuse profonde ?', options: [{ l: 'A', t: 'Terrain atopique' }, { l: 'B', t: 'Antécédent récent d\'hémorragie intracérébrale (moins de 6 jours)' }, { l: 'C', t: 'Antécédent de thrombopénie immuno-allergique induite par l\'héparine' }, { l: 'D', t: 'Insuffisance rénale avec clairance de la créatinine inférieure à 15 mL/min (Cockcroft et Gault)' }, { l: 'E', t: 'Traitement par un anti-agrégant plaquettaire' }], answer: 'BCD', chapterSlugs: ["iv-37-surveillance-heparines-avk"], programItems: ["IV-37"] },
    { n: 31, type: 'qcm', prompt: 'Parmi les bactéries suivantes, laquelle (lesquelles) est (sont) responsable(s) d\'une méningite néonatale ?', options: [{ l: 'A', t: 'Listeria monocytogenes' }, { l: 'B', t: 'Neisseria meningitidis' }, { l: 'C', t: 'Escherichia coli' }, { l: 'D', t: 'Streptococcus pyogenes' }, { l: 'E', t: 'Streptococcus agalactiae' }], answer: 'ACE', chapterSlugs: ["iv-1-infections-snc"], programItems: ["IV-1"] },
    { n: 32, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la toxoplasmose humaine, indiquer celle(s) qui est (sont) exacte(s)', options: [{ l: 'A', t: 'Elle est souvent asymptomatique chez l\'immunocompétent' }, { l: 'B', t: 'Elle se caractérise par des calcifications intracérébrales, dans sa forme congénitale' }, { l: 'C', t: 'Elle se contracte par ingestion de viande crue contenant des kystes tissulaires' }, { l: 'D', t: 'Elle se contracte par ingestion d\'oocystes infectants' }, { l: 'E', t: 'Elle se traite par le flubendazole' }], answer: 'ABCD', chapterSlugs: ["iv-15-toxoplasmose"], programItems: ["IV-15"] },
    { n: 33, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les établissements de santé privés, lesquelles sont exactes ?', options: [{ l: 'A', t: 'Ils doivent participer à l\'aide médicale urgente' }, { l: 'B', t: 'Ils doivent contribuer à la recherche clinique' }, { l: 'C', t: 'Ils doivent mener une réflexion éthique liée à l\'accueil et la prise en charge médicale' }, { l: 'D', t: 'Ils doivent participer à la mise en œuvre des dispositifs de vigilance des produits de santé' }, { l: 'E', t: 'Ils doivent participer à la formation initiale des professionnels de santé' }], answer: 'CD', chapterSlugs: ["iii-7-etablissements-sante-pui"], programItems: ["III-7"] },
    { n: 34, type: 'qcm', prompt: 'Parmi les médicaments suivants, quel(s) est (sont) celui (ceux) indiqué(s) dans la prise en charge de l\'insuffisance cardiaque ?', options: [{ l: 'A', t: 'Enalapril' }, { l: 'B', t: 'Nifédipine' }, { l: 'C', t: 'Carvédilol' }, { l: 'D', t: 'Spironolactone' }, { l: 'E', t: 'Furosémide' }], answer: 'ACDE', chapterSlugs: ["v-12-insuffisance-cardiaque"], programItems: ["V-12"] },
    { n: 35, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les dihydropyridines antagonistes calciques, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Elles sont responsables d\'un effet inotrope négatif' }, { l: 'B', t: 'Elles ont un effet vasodilatateur' }, { l: 'C', t: 'Elles peuvent être associées aux bêta-bloquants' }, { l: 'D', t: 'Elles peuvent provoquer des céphalées' }, { l: 'E', t: 'Elles sont indiquées dans le traitement de l\'hypertension artérielle' }], answer: 'BCDE', chapterSlugs: ["v-6-effet-dose-marge-therapeutique"], programItems: ["V-6"] },
    { n: 36, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la glucose-6-phosphatase, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'C\'est une enzyme de localisation musculaire' }, { l: 'B', t: 'Elle participe à la dernière étape de la gluconéogenèse' }, { l: 'C', t: 'Elle est activée en période de jeûne' }, { l: 'D', t: 'Elle intervient dans l\'homéostasie de la glycémie' }, { l: 'E', t: 'Elle catalyse la phosphorylation du glucose intracellulaire' }], answer: 'BCD', chapterSlugs: ["ii-11-biochimie-regulation-glycemie"], programItems: ["II-11"] },
    { n: 37, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les inhibiteurs physiologiques de la coagulation, quelle(s) est (sont) celle(s) qui est (sont) exacte(s) ?', options: [{ l: 'A', t: 'L\'antithrombine inhibe le facteur Xa' }, { l: 'B', t: 'La protéine S est le cofacteur de la protéine C activée' }, { l: 'C', t: 'Le complexe thrombine-thrombomoduline active l\'antithrombine' }, { l: 'D', t: 'La protéine C activée inactive les facteurs Va et VIIIa' }, { l: 'E', t: 'Un déficit en antithrombine est associé à une pathologie hémorragique' }], answer: 'ABD', chapterSlugs: ["ii-26-physiologie-hemostase"], programItems: ["II-26"] },
    { n: 38, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant les méthodes spectrales d\'analyse, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Le coefficient d\'absorption molaire dépend de la longueur d\'onde du rayonnement incident' }, { l: 'B', t: 'La fluorescence est un phénomène plus rapide que la phosphorescence' }, { l: 'C', t: 'L\'énergie des rayonnements infrarouges est supérieure à celle des rayonnements ultraviolets' }, { l: 'D', t: 'La longueur d\'onde à laquelle l\'absorption est maximale est indépendante du solvant' }, { l: 'E', t: 'Un spectrophotomètre double-faisceau permet de s\'affranchir de l\'absorption liée au solvant' }], answer: 'ABE', chapterSlugs: ["i-2-spectrophotometrie-atomique"], programItems: ["I-2"] },
    { n: 39, type: 'qcm', prompt: 'Parmi les propositions suivantes, lesquelles sont exactes ? La pharmacovigilance vise à identifier, évaluer, prévenir les risques liés', options: [{ l: 'A', t: 'Aux vaccins' }, { l: 'B', t: 'Aux produits sanguins stables' }, { l: 'C', t: 'Aux produits sanguins labiles' }, { l: 'D', t: 'Aux médicaments en accès précoce' }, { l: 'E', t: 'Aux préparations magistrales' }], answer: 'ABDE', chapterSlugs: ["iv-38-produits-sanguins-labiles"], programItems: ["IV-38"] },
    { n: 40, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'éthanol, quelle(s) est (sont) celle(s) qui est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Il est complètement résorbé au niveau gastrique' }, { l: 'B', t: 'Le pic plasmatique de l\'éthanol est atteint en 30 à 90 min' }, { l: 'C', t: 'L\'alcoolémie diminue plus rapidement chez l\'alcoolo-dépendant que chez le buveur occasionnel' }, { l: 'D', t: '30 à 40 % de l\'éthanol ingéré sont éliminés sous forme non métabolisée par voie respiratoire' }, { l: 'E', t: 'Il est transformé en acétaldéhyde par l\'alcool déshydrogénase' }], answer: 'BCE', chapterSlugs: ["iii-11-toxicologie-alcools"], programItems: ["III-11"] },
    { n: 41, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'omalizumab, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'C\'est un anticorps monoclonal humanisé' }, { l: 'B', t: 'Il empêche la libération des médiateurs préformés mastocytaires' }, { l: 'C', t: 'Il est indiqué dans l\'asthme allergique sévère' }, { l: 'D', t: 'Sa posologie est adaptée en fonction de la concentration sérique initiale en immunoglobulines E' }, { l: 'E', t: 'Il est utilisable par voie orale' }], answer: 'ABCD', chapterSlugs: ["ii-27-immunologie-immunoglobulines"], programItems: ["II-27"] },
    { n: 42, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le détecteur à barette de diodes (détecteur utilisé en chromatographie liquide), quelles sont celles qui sont exactes ?', options: [{ l: 'A', t: 'Son utilisation impose un traitement informatique du signal' }, { l: 'B', t: 'La cellule de détection reçoit une lumière monochromatique' }, { l: 'C', t: 'Il permet d\'acquérir simultanément absorbance et longueur d\'onde' }, { l: 'D', t: 'Il permet d\'accéder au spectre d\'absorbance de chaque pic chromatographique' }, { l: 'E', t: 'Un pic chromatographique correspond à un soluté unique si les spectres sont identiques à différents niveaux du pic' }], answer: 'ACDE', chapterSlugs: ["i-1-extraction-separation"], programItems: ["I-1"] },
    { n: 43, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le lanzoprazole, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Il est utilisé en prévention des lésions gastroduodénales induites par les anti-inflammatoires non stéroïdiens' }, { l: 'B', t: 'Sa structure est modifiée en milieu acide' }, { l: 'C', t: 'C\'est un antagoniste des récepteurs H2' }, { l: 'D', t: 'C\'est un dérivé du benzimidazole' }, { l: 'E', t: 'Il peut être utilisé dans l\'éradication d\'Helicobacter pylori' }], answer: 'ABDE', chapterSlugs: ["v-5-cibles-recepteurs"], programItems: ["V-5"] },
    { n: 44, type: 'qcm', prompt: 'Quelle(s) est (sont) la (les) proposition(s) exacte(s) ? La vaccination contre la tuberculose est recommandée en France pour un enfant', options: [{ l: 'A', t: 'Né dans un pays de forte endémie tuberculeuse' }, { l: 'B', t: 'Dont l\'un au moins des parents est originaire d\'un pays de forte endémie tuberculeuse' }, { l: 'C', t: 'Devant séjourner au moins un mois d\'affilée dans un pays de forte endémie tuberculeuse' }, { l: 'D', t: 'Résidant en milieu urbain' }, { l: 'E', t: 'Jugé à risque par le médecin en raison de conditions défavorables de logement' }], answer: 'ABCE', chapterSlugs: ["i-13-protometrie-milieu-non-aqueux"], programItems: ["I-13"] },
    { n: 45, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le benzène, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Sa densité de vapeur est plus élevée que celle de l\'air' }, { l: 'B', t: 'L\'acide trans,trans-muconique est l\'un de ses métabolites' }, { l: 'C', t: 'Il a une toxicité chronique voisine de celle du toluène' }, { l: 'D', t: 'C\'est un inducteur enzymatique' }, { l: 'E', t: 'Sa mesure dans l\'air expiré est un bon indicateur d\'exposition récente' }], answer: 'ABDE', chapterSlugs: ["ii-7-enzymologie-mesure-activite-enzymatique"], programItems: ["II-7"] },
    { n: 46, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la radioactivité, quelle(s) est (sont) celle(s) qui est (sont) exacte(s) ?', options: [{ l: 'A', t: 'La somme des masses des constituants d\'un noyau pris séparément est plus importante que la masse de ce noyau' }, { l: 'B', t: 'L\'instabilité d\'un noyau due à un excès de neutrons peut se corriger par émission bêta plus' }, { l: 'C', t: 'Dans un mélange de deux radionucléides différents, il y a enrichissement progressif en radionucléide dont la période est la plus grande' }, { l: 'D', t: 'La trajectoire des particules bêta moins dans la matière est en ligne droite' }, { l: 'E', t: 'Le transfert d\'énergie linéique est plus grand pour les particules bêta que pour les particules alpha' }], answer: 'AC', chapterSlugs: ["v-24-beta-lactames"], programItems: ["V-24"] },
    { n: 47, type: 'qcm', prompt: 'Parmi les examens biologiques suivants, quels sont ceux qui sont recommandés pour le diagnostic d\'une polyarthrite rhumatoïde ?', options: [{ l: 'A', t: 'Le typage HLA de classe I' }, { l: 'B', t: 'Le dosage de la CRP' }, { l: 'C', t: 'La recherche des facteurs rhumatoïdes' }, { l: 'D', t: 'La recherche d\'anticorps anti-peptides citrullinés (CCP)' }, { l: 'E', t: 'Le dosage des IgE totales' }], answer: 'BCD', chapterSlugs: ["iv-33-maladies-auto-immunes"], programItems: ["IV-33"] },
    { n: 48, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la préparation ophtalmique de ciclosporine à 1 mg/ml contenant les excipients ci-dessous, laquelle (lesquelles) est (sont) exacte(s) ? Triglycérides à chaine moyenne, glycérol, chlorure de cétalkonium, poloxamère 188, hydroxyde de sodium, eau pour préparations injectables', options: [{ l: 'A', t: 'Cette préparation est une solution aqueuse' }, { l: 'B', t: 'Le poloxamère 188 est un surfactant' }, { l: 'C', t: 'L\'hydroxyde de sodium permet de tamponner la préparation' }, { l: 'D', t: 'Le glycérol est un isotonisant' }, { l: 'E', t: 'La concentration en principe actif est de 1 %' }], answer: 'BD', chapterSlugs: ["v-51-formes-liberation-conventionnelle"], programItems: ["V-51"] },
    { n: 49, type: 'qcm', prompt: 'Parmi les mécanismes impliqués dans la régulation de l\'expression des gènes, lequel (lesquels) peut (peuvent) intervenir dans la maturation des transcrits primaires ?', options: [{ l: 'A', t: 'Présence de promoteurs alternatifs' }, { l: 'B', t: 'Epissage alternatif' }, { l: 'C', t: 'Présence de régions régulatrices en "cis"' }, { l: 'D', t: 'Présence de sites multiples de poly-adénylation' }, { l: 'E', t: 'Modifications chimiques' }], answer: 'BD', chapterSlugs: ["ii-2-genetique-regulation-expression-genes"], programItems: ["II-2"] },
    { n: 50, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant le séquençage des acides nucléiques par la méthode de Sanger, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Il permet de mettre en évidence des substitutions nucléotidiques de type SNP' }, { l: 'B', t: 'Il permet de mettre en évidence des mutations dues à des transitions' }, { l: 'C', t: 'Il permet de mettre en évidence des mutations dues à des délétions de quelques nucléotides' }, { l: 'D', t: 'Il permet la caractérisation de variations nucléotidiques au sein de la séquence d\'un exon' }, { l: 'E', t: 'Il permet la caractérisation de variations nucléotidiques au sein de la séquence d\'un intron' }], answer: 'ABCDE', chapterSlugs: ["ii-4-genetique-identification-mutations"], programItems: ["II-4"] },
    { n: 51, type: 'qcm', prompt: 'Parmi les propositions suivantes, concernant la rétrocession, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Elle est organisée exclusivement pour les patients non hospitalisés, bénéficiaires de l\'Aide Médicale d\'Etat' }, { l: 'B', t: 'Elle est organisée dans toutes les pharmacies à usage intérieur des établissements de santé' }, { l: 'C', t: 'Elle constitue une dérogation au monopole pharmaceutique de distribution' }, { l: 'D', t: 'Elle doit être réalisée par un pharmacien ou par un préparateur sous le contrôle d\'un pharmacien' }, { l: 'E', t: 'Elle ne concerne que des médicaments non disponibles en officine de ville' }], answer: 'D', chapterSlugs: ["iii-7-etablissements-sante-pui"], programItems: ["III-7"] },
    { n: 52, type: 'qcm', prompt: 'Parmi les propositions suivantes relatives à la présentation de l\'antigène par les molécules du complexe majeur d\'histocompatibilité (CMH) de classe I, quelle(s) est (sont) celle(s) qui est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Elle implique le clivage d\'une protéine en peptides de petite taille' }, { l: 'B', t: 'Elle implique l\'interaction avec les lymphocytes T CD4+' }, { l: 'C', t: 'Les complexes CMH - peptides sont exportés vers la membrane de la cellule présentatrice de l\'antigène' }, { l: 'D', t: 'Le choix du peptide sélectionné dépend du variant allélique de la molécule de CMH' }, { l: 'E', t: 'Elle est réalisée uniquement par les cellules dendritiques' }], answer: 'ACD', chapterSlugs: ["ii-29-immunologie-cmh-presentation-antigene"], programItems: ["II-29"] },
    { n: 53, type: 'qcm', prompt: 'Quel(s) signe(s) clinique(s) peut-on observer lors d\'une intoxication aiguë par les neuroleptiques ?', options: [{ l: 'A', t: 'Un syndrome extrapyramidal' }, { l: 'B', t: 'Un syndrome cholinergique' }, { l: 'C', t: 'Une mydriase' }, { l: 'D', t: 'Des myoclonies' }, { l: 'E', t: 'Une hyper-salivation' }], answer: 'ACDE', chapterSlugs: ["iv-46-insuffisance-renale"], programItems: ["IV-46"] },
    { n: 54, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'accès palustre simple à Plasmodium falciparum, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Il se caractérise cliniquement par la triade frissons, fièvre, sueurs' }, { l: 'B', t: 'Il se traite en première intention par de l\'artesunate' }, { l: 'C', t: 'Il peut se traiter par l\'association arthéméther-luméfantrine' }, { l: 'D', t: 'Il peut se traiter par la doxycycline' }, { l: 'E', t: 'Il s\'accompagne de troubles de la conscience' }], answer: 'AC', chapterSlugs: ["iv-3-infections-urinaires"], programItems: ["IV-3"] },
    { n: 55, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'évaluation règlementaire de la toxicité réitérée d\'un médicament, quelle(s) est (sont) celle(s) qui est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Les études sur animaux précèdent les essais cliniques chez l\'Homme' }, { l: 'B', t: 'Elle a pour objectif de déterminer la NOAEL (No Observed Adverse Effect Level) du produit testé' }, { l: 'C', t: 'Les études doivent être réalisées sur au moins 2 espèces de mammifères rongeurs' }, { l: 'D', t: 'L\'administration du produit testé doit se faire par la voie prévue chez l\'Homme' }, { l: 'E', t: 'La durée de l\'essai chez l\'animal est fonction de la durée prévue d\'administration chez l\'Homme' }], answer: 'ABDE', chapterSlugs: ["v-44-evaluation-toxicite"], programItems: ["V-44"] },
    { n: 56, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la sécurité virale des médicaments dérivés du sang, quelles sont les techniques utilisées ?', options: [{ l: 'A', t: 'La microfiltration' }, { l: 'B', t: 'L\'autoclavage' }, { l: 'C', t: 'La pasteurisation' }, { l: 'D', t: 'La combinaison d\'un solvant et d\'un détergent' }, { l: 'E', t: 'L\'ajout de conservateurs antimicrobiens' }], answer: 'CD', chapterSlugs: ["v-56-medicaments-derives-plasma"], programItems: ["V-56"] },
    { n: 57, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la prise en charge de l\'ostéoporose, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Le dénosumab inhibe sélectivement l\'activation du récepteur RANK à la surface des ostéoclastes' }, { l: 'B', t: 'Le tériparatide est composé d\'une séquence d\'acides aminés de l\'extrémité amino-terminale de la parathormone humaine' }, { l: 'C', t: 'Le raloxifène est un antagoniste pur des récepteurs œstrogéniques' }, { l: 'D', t: 'Les biphosphonates sont éliminés sous forme inchangée dans les urines' }, { l: 'E', t: 'Les biphosphonates doivent être administrés au milieu du repas' }], answer: 'ABD', chapterSlugs: ["v-5-cibles-recepteurs"], programItems: ["V-5"] },
    { n: 58, type: 'qcm', prompt: 'Concernant le mécanisme d\'action des antidotes suivants, quelle(s) proposition(s) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'Le fomépizole sature l\'alcool déshydrogénase' }, { l: 'B', t: 'La pralidoxime réactive les cholinestérases' }, { l: 'C', t: 'La naloxone est un agoniste morphinique partiel' }, { l: 'D', t: 'La N-acétylcystéine reconstitue le stock de glutathion réduit' }, { l: 'E', t: 'L\'acide dimercaptosuccinique chélate le mercure' }], answer: 'BDE', chapterSlugs: ["i-12-acide-base-ph-tampons"], programItems: ["I-12"] },
    { n: 59, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant l\'intérêt des peptides natriurétiques dans l\'insuffisance cardiaque, laquelle (lesquelles) est (sont) exacte(s) ?', options: [{ l: 'A', t: 'La valeur des peptides natriurétiques cardiaques est corrélée à la gravité de l\'insuffisance cardiaque' }, { l: 'B', t: 'Le dosage des peptides natriurétiques cardiaques est indispensable au diagnostic' }, { l: 'C', t: 'Le NT-proBNP présente une valeur diagnostique supérieure au BNP' }, { l: 'D', t: 'Le dosage des peptides natriurétiques cardiaques est indispensable pour le suivi thérapeutique de l\'insuffisant cardiaque' }, { l: 'E', t: 'L\'âge n\'a pas d\'influence sur les valeurs usuelles des peptides natriurétiques' }], answer: 'A', chapterSlugs: ["iv-47-sca-insuffisance-cardiaque"], programItems: ["IV-47"] },
    { n: 60, type: 'qcm', prompt: 'Parmi les propositions suivantes concernant la spectrofluorimétrie moléculaire, lesquelles sont exactes ?', options: [{ l: 'A', t: 'Le rendement quantique augmente avec la conjugaison électronique du fluorophore' }, { l: 'B', t: 'La durée de vie de fluorescence excède la seconde' }, { l: 'C', t: 'Le phénomène de fluorescence fait intervenir le niveau triplet excité (T1) du fluorophore' }, { l: 'D', t: 'L\'intensité de fluorescence augmente avec la planéité du fluorophore' }, { l: 'E', t: 'En solution très diluée, l\'intensité de fluorescence est directement proportionnelle à la concentration de la substance fluorescente EPREUVE DE DOSSIERS THERAPEUTIQUES ET BIOLOGIQUES Dossier N° 1 Enoncé Madame D., 46 ans, sans domicile fixe, est hospitalisée aux urgences pour confusion mentale. Elle est alcoolo-tabagique. L\'examen clinique met en évidence une discrète ascite, des œdèmes des membres inférieurs, une splénomégalie. Les examens biochimiques révèlent une augmentation importante de l\'activité des enzymes hépatiques (ASAT, ALAT et gamma-GT). Les résultats du bilan hématologique sont les suivants : Hémogramme : - Sg Erythrocytes : 3,20 T/L - Sg Hémoglobine : 110 g/L - Sg Hématocrite : 0,34 - Sg Leucocytes : 3,6 G/L - Sg Plaquettes : 110 G/L - Formule leucocytaire : - Polynucléaires neutrophiles : 50 % - Polynucléaires éosinophiles : 2 % - Polynucléaires basophiles : 1 % - Lymphocytes : 40 % - Monocytes : 7 % Bilan d\'hémostase : - Pl Activité du complexe prothrombinique (TP) : 40 % - Pl Temps de céphaline avec activateur : 52 s (Témoin = 38 s) - Pl Fibrinogène : 1,50 g/L - Pl Facteur V : 30 % - Pl Facteur VII : 38 % - Pl Facteur X : 38 % - Pl Facteur II : 40 % Les sérologies virales pour les virus hépatotropes sont négatives. Questions' }], answer: 'ADE', chapterSlugs: ["i-4-spectrofluorimetrie"], programItems: ["I-4"] }
    ]
  }
];

/** Tous les items, aplatis, avec leur session. */
export const allAnnales = annalesSessions.flatMap((s) =>
  s.items.map((it) => ({ ...it, session: s.key, sessionLabel: s.label }))
);

/** Items d'annales rattachés à un chapitre donné. */
export function annalesForChapter(slug) {
  if (!slug) return [];
  return allAnnales.filter((it) => it.chapterSlugs.includes(slug));
}

/** Nombre d'items par session (pour l'index). */
export function annalesStats() {
  return annalesSessions.map((s) => ({
    key: s.key,
    label: s.label,
    total: s.items.length,
    qcm: s.items.filter((i) => i.type === 'qcm').length,
    dossiers: s.items.filter((i) => i.type === 'dossier').length,
    exercices: s.items.filter((i) => i.type === 'exercice').length
  }));
}
