// @ts-nocheck
// Pathologies du domaine — voir lexique.js pour le format.
export const pathologies = [
  { id: 'pericardite-aigue', nom: 'Péricardite aiguë', discipline: 'Cardiologie',
    cles: ['douleur thoracique', 'fièvre', 'douleur augmentée à l\'inspiration', 'douleur soulagée par l\'antéflexion', 'frottement péricardique', 'sus-décalage ST diffus concave', 'troponine élevée'],
    orientation: "Douleur thoracique majorée à l'inspiration et soulagée par l'antéflexion + frottement péricardique + sus-décalage ST diffus concave = péricardite aiguë (souvent virale) : ECG, écho cœur pour éliminer un épanchement." },
  { id: 'dissection-aortique', nom: 'Dissection aortique', discipline: 'Cardiologie',
    cles: ['douleur thoracique', 'douleur thoracique migratrice', 'terrain vasculaire', 'asymétrie tensionnelle', 'malaise', 'syncope', 'sueurs'],
    orientation: "Douleur thoracique brutale en coup de poignard, transfixiante et migratrice + asymétrie tensionnelle aux deux bras = dissection aortique : angioscanner thoracique en urgence, contrôle tensionnel." },
  { id: 'urgence-hypertensive', nom: 'Urgence hypertensive', discipline: 'Cardiologie',
    cles: ['céphalées', 'douleur thoracique', 'dyspnée', 'troubles visuels', 'malaise', 'terrain vasculaire', 'sujet âgé'],
    orientation: "PA très élevée + souffrance viscérale (céphalées, troubles visuels, dyspnée, douleur thoracique) = urgence hypertensive : baisse progressive de la PA, recherche d'un retentissement (OAP, SCA, AVC)." },
  { id: 'fibrillation-atriale', nom: 'Fibrillation atriale', discipline: 'Cardiologie',
    cles: ['palpitations', 'tachycardie', 'pouls irrégulier', 'dyspnée', 'malaise', 'sujet âgé', 'facteur de risque de thrombose'],
    orientation: "Palpitations + pouls irrégulier + arythmie complète à l'ECG = fibrillation atriale : évaluation du risque embolique (score CHA2DS2-VASc) et anticoagulation." },
  { id: 'retrecissement-aortique', nom: 'Rétrécissement aortique', discipline: 'Cardiologie',
    cles: ['dyspnée', 'douleur thoracique', 'syncope', 'syncope d\'effort', 'souffle systolique éjectionnel', 'palpitations', 'sujet âgé'],
    orientation: "Triade angor - syncope d'effort - dyspnée + souffle systolique éjectionnel irradiant aux carotides chez le sujet âgé = rétrécissement aortique serré : écho cœur." },
  { id: 'insuffisance-mitrale', nom: 'Insuffisance mitrale', discipline: 'Cardiologie',
    cles: ['dyspnée', 'orthopnée', 'œdèmes', 'palpitations', 'souffle systolique', 'souffle irradiant à l\'aisselle', 'asthénie'],
    orientation: "Dyspnée d'effort + souffle holosystolique apexien irradiant vers l'aisselle = insuffisance mitrale : écho cœur pour quantifier la fuite et évaluer le retentissement." },
  { id: 'thrombose-veineuse-profonde', nom: 'Thrombose veineuse profonde', discipline: 'Cardiologie',
    cles: ['œdème unilatéral du mollet', 'douleur du mollet', 'immobilisation', 'facteur de risque de thrombose', 'terrain vasculaire', 'mollet chaud et rouge', 'diminution du ballant du mollet'],
    orientation: "Œdème unilatéral, chaud et douloureux du mollet + facteur de risque de thrombose (immobilisation, chirurgie) = TVP : écho-doppler veineux, attention à l'embolie pulmonaire." },
  { id: 'bpco-exacerbation', nom: 'BPCO en exacerbation', discipline: 'Pneumologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['dyspnée', 'toux', 'expectoration purulente', 'tabac', 'sifflements', 'majoration de la dyspnée', 'fièvre'],
    orientation: "Aggravation de la dyspnée + expectoration devenue purulente chez un patient tabagique BPCO connu = exacerbation, souvent d'origine infectieuse : oxygène prudent, bronchodilatateurs, antibiothérapie si purulence." },
  { id: 'asthme-aigu-grave', nom: 'Asthme aigu grave', discipline: 'Pneumologie',
    cles: ['dyspnée', 'sifflements', 'toux', 'difficulté à parler', 'orthopnée', 'tachycardie', 'silence auscultatoire'],
    orientation: "Crise d'asthme avec difficulté à parler, orthopnée, tachycardie et surtout silence auscultatoire = asthme aigu grave : DEP effondré, bronchodilatateurs en nébulisation + corticoïdes, urgence vitale." },
  { id: 'pneumothorax', nom: 'Pneumothorax', discipline: 'Pneumologie',
    cles: ['douleur thoracique', 'douleur thoracique brutale', 'dyspnée', 'toux', 'abolition du murmure vésiculaire', 'tympanisme', 'sujet jeune longiligne'],
    orientation: "Douleur latéro-thoracique brutale + dyspnée avec abolition du murmure vésiculaire et tympanisme unilatéral, sujet jeune longiligne = pneumothorax : radiographie thoracique, drainage si mauvaise tolérance." },
  { id: 'pleuresie', nom: 'Pleurésie (épanchement pleural)', discipline: 'Pneumologie',
    cles: ['dyspnée', 'douleur thoracique', 'toux', 'fièvre', 'matité déclive', 'abolition du murmure vésiculaire', 'diminution des vibrations vocales'],
    orientation: "Dyspnée + matité déclive avec abolition du murmure vésiculaire et diminution des vibrations vocales = épanchement pleural : radiographie, ponction pleurale pour préciser la cause (infectieuse, néoplasique)." },
  { id: 'hypertension-arterielle-pulmonaire', nom: 'Hypertension artérielle pulmonaire', discipline: 'Pneumologie',
    cles: ['dyspnée', 'dyspnée d\'effort', 'syncope', 'syncope d\'effort', 'œdèmes', 'signes d\'insuffisance cardiaque droite', 'asthénie'],
    orientation: "Dyspnée d'effort d'aggravation progressive + signes d'insuffisance cardiaque droite (œdèmes, éclat de B2 pulmonaire), parfois syncope d'effort = HTAP : écho cœur puis cathétérisme droit." },
  { id: 'anevrisme-aorte', nom: 'Anévrisme de l\'aorte abdominale', discipline: 'Cardiologie',
    cles: ['douleur abdominale', 'masse abdominale battante', 'terrain vasculaire', 'tabac', 'sujet âgé', 'hypotension', 'malaise'],
    orientation: "Masse abdominale battante et expansive chez un homme âgé tabagique = anévrisme de l'aorte abdominale ; une douleur brutale avec hypotension évoque la rupture : angioscanner en urgence." },
  { id: 'aomi', nom: 'Artériopathie oblitérante des membres inférieurs', discipline: 'Cardiologie',
    cles: ['claudication intermittente', 'douleur du mollet à la marche', 'terrain vasculaire', 'tabac', 'abolition des pouls périphériques', 'sujet âgé', 'facteur de risque de thrombose'],
    orientation: "Douleur du mollet à la marche cédant au repos (claudication intermittente) + abolition des pouls périphériques chez un patient tabagique = AOMI : mesure de l'index de pression systolique, écho-doppler artériel." },
  { id: 'oedeme-aigu-poumon', nom: 'Œdème aigu du poumon', discipline: 'Cardiologie', chapter: 'iv-47-sca-insuffisance-cardiaque',
    cles: ['dyspnée', 'orthopnée', 'toux', 'expectoration mousseuse', 'crépitants bilatéraux', 'sueurs', 'tachycardie'],
    orientation: "Dyspnée brutale + orthopnée + crépitants bilatéraux en marée montante avec expectoration mousseuse rosée = OAP cardiogénique (insuffisance cardiaque gauche aiguë) : position assise, diurétiques, dérivés nitrés, oxygène." },
];
