// @ts-nocheck
// Pathologies du domaine — voir lexique.js pour le format.
export const pathologies = [
  // ─── Hépato-gastro-entérologie ───
  { id: 'hemorragie-digestive', nom: 'Hémorragie digestive', discipline: 'Hépato-gastro',
    cles: ['hématémèse', 'méléna', 'anémie', 'alcool', 'douleur abdominale', 'vomissements'],
    orientation: "Hématémèse et/ou méléna avec déglobulisation = hémorragie digestive : endoscopie en urgence après stabilisation hémodynamique (rupture de varices si cirrhose)." },
  { id: 'ulcere-gastroduodenal', nom: 'Ulcère gastro-duodénal', discipline: 'Hépato-gastro',
    cles: ['douleur abdominale', 'douleur épigastrique', 'hématémèse', 'méléna', 'tabac', 'vomissements'],
    orientation: "Douleur épigastrique rythmée par les repas (crampe post-prandiale calmée par l'alimentation) = ulcère gastro-duodénal : FOGD + recherche d'Helicobacter pylori." },
  { id: 'rgo', nom: 'Reflux gastro-œsophagien', discipline: 'Hépato-gastro',
    cles: ['pyrosis', 'régurgitations', 'douleur abdominale', 'dysphagie', 'toux', 'brûlures rétrosternales'],
    orientation: "Pyrosis et régurgitations acides majorés en décubitus et après les repas = reflux gastro-œsophagien ; FOGD si signes d'alarme (dysphagie, amaigrissement, anémie)." },
  { id: 'hepatite-alcoolique', nom: 'Hépatite alcoolique aiguë', discipline: 'Hépato-gastro', chapter: 'iv-44-cholestase-cytolyse',
    cles: ['ictère', 'alcool', 'cytolyse', 'fièvre', 'douleur abdominale', 'ascite', 'amaigrissement'],
    orientation: "Ictère fébrile avec cytolyse modérée (ASAT > ALAT) chez un consommateur d'alcool = hépatite alcoolique aiguë ; score de Maddrey pour l'indication à la corticothérapie." },
  { id: 'angiocholite', nom: 'Angiocholite (lithiase de la voie biliaire)', discipline: 'Hépato-gastro', chapter: 'iv-44-cholestase-cytolyse',
    cles: ['fièvre', 'ictère', 'douleur abdominale', 'frissons', 'cholestase', 'cytolyse'],
    orientation: "Triade de Charcot (douleur de l'hypochondre droit + fièvre avec frissons + ictère) = angiocholite sur obstacle lithiasique : urgence de désobstruction biliaire." },
  { id: 'appendicite', nom: 'Appendicite aiguë', discipline: 'Hépato-gastro',
    cles: ['douleur abdominale', 'fièvre', 'vomissements', 'sujet jeune', 'défense', 'nausées'],
    orientation: "Douleur de la fosse iliaque droite avec défense, fièvre modérée et hyperleucocytose = appendicite aiguë : indication chirurgicale." },
  { id: 'occlusion-intestinale', nom: 'Occlusion intestinale', discipline: 'Hépato-gastro',
    cles: ['douleur abdominale', 'vomissements', 'constipation', 'arrêt des matières et des gaz', 'météorisme', 'sujet âgé'],
    orientation: "Douleur abdominale + vomissements + arrêt des matières et des gaz + météorisme = syndrome occlusif : ASP/TDM pour situer le niveau et le mécanisme." },
  { id: 'crohn', nom: 'Maladie de Crohn', discipline: 'Hépato-gastro',
    cles: ['diarrhée', 'douleur abdominale', 'amaigrissement', 'sujet jeune', 'lésions anales', 'anémie'],
    orientation: "Diarrhée chronique + douleurs abdominales + amaigrissement + lésions ano-périnéales chez un sujet jeune = maladie de Crohn (atteinte segmentaire et transmurale)." },
  { id: 'rch', nom: 'Rectocolite hémorragique', discipline: 'Hépato-gastro',
    cles: ['diarrhée', 'rectorragies', 'douleur abdominale', 'sujet jeune', 'syndrome rectal', 'glaires'],
    orientation: "Diarrhée glairo-sanglante avec syndrome rectal, évoluant par poussées chez un sujet jeune = rectocolite hémorragique (atteinte continue rectocolique)." },
  { id: 'diverticulite', nom: 'Diverticulite sigmoïdienne', discipline: 'Hépato-gastro',
    cles: ['douleur abdominale', 'fièvre', 'sujet âgé', 'constipation', 'défense', 'troubles du transit'],
    orientation: "Douleur de la fosse iliaque gauche fébrile chez un sujet âgé = diverticulite sigmoïdienne : TDM abdominale (pas de coloscopie en phase aiguë)." },
  { id: 'cancer-colorectal', nom: 'Cancer colorectal', discipline: 'Hépato-gastro',
    cles: ['méléna', 'anémie', 'amaigrissement', 'antécédents familiaux', 'sujet âgé', 'troubles du transit', 'rectorragies'],
    orientation: "Anémie ferriprive, rectorragies ou modification récente du transit après 50 ans = cancer colorectal jusqu'à preuve du contraire : coloscopie totale avec biopsies." },
  { id: 'hepatite-auto-immune', nom: 'Hépatite auto-immune', discipline: 'Hépato-gastro', chapter: 'iv-44-cholestase-cytolyse',
    cles: ['ictère', 'cytolyse', 'amaigrissement', 'asthénie', 'auto-anticorps', 'femme jeune'],
    orientation: "Cytolyse chronique avec hypergammaglobulinémie et auto-anticorps (anti-muscle lisse, anti-LKM1), volontiers chez la femme jeune = hépatite auto-immune." },

  // ─── Neurologie ───
  { id: 'avc', nom: 'Accident vasculaire cérébral', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['déficit neurologique', 'terrain vasculaire', 'troubles de conscience', 'céphalées', 'sujet âgé', 'aphasie'],
    orientation: "Déficit neurologique focal d'installation brutale = AVC : imagerie cérébrale en urgence pour distinguer ischémie et hémorragie (fenêtre de thrombolyse)." },
  { id: 'epilepsie', nom: 'Épilepsie (crise convulsive)', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['convulsions', 'troubles de conscience', 'perte de connaissance', 'morsure de langue', 'confusion post-critique', 'mouvements tonico-cloniques'],
    orientation: "Crise tonico-clonique avec morsure latérale de langue et confusion post-critique = crise d'épilepsie ; EEG et imagerie cérébrale pour l'étiologie." },
  { id: 'migraine', nom: 'Migraine', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['céphalées', 'nausées', 'vomissements', 'photophobie', 'aura', 'céphalée pulsatile'],
    orientation: "Céphalée pulsatile unilatérale récidivante avec photophobie et nausées, parfois précédée d'une aura visuelle = migraine (pas de déficit neurologique durable)." },
  { id: 'parkinson', nom: 'Maladie de Parkinson', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['tremblement de repos', 'sujet âgé', 'akinésie', 'rigidité', 'lenteur', 'troubles de la marche'],
    orientation: "Triade tremblement de repos + rigidité + akinésie, asymétrique et sensible à la L-dopa = maladie de Parkinson (syndrome extrapyramidal)." },
  { id: 'alzheimer', nom: 'Maladie d\'Alzheimer', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['troubles de la mémoire', 'sujet âgé', 'désorientation', 'troubles du comportement', 'aphasie', 'perte d\'autonomie'],
    orientation: "Troubles mnésiques d'installation progressive avec désorientation et retentissement sur l'autonomie chez le sujet âgé = maladie d'Alzheimer." },
  { id: 'sep', nom: 'Sclérose en plaques', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['déficit neurologique', 'troubles visuels', 'femme jeune', 'paresthésies', 'poussées', 'troubles de l\'équilibre'],
    orientation: "Épisodes neurologiques régressifs disséminés dans le temps et l'espace chez une femme jeune (névrite optique, troubles sensitifs) = sclérose en plaques : IRM." },
  { id: 'guillain-barre', nom: 'Syndrome de Guillain-Barré', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['déficit neurologique', 'paresthésies', 'déficit moteur', 'aréflexie', 'épisode infectieux récent', 'troubles de la déglutition'],
    orientation: "Déficit moteur bilatéral ascendant avec aréflexie, au décours d'un épisode infectieux = syndrome de Guillain-Barré : surveiller la fonction respiratoire (dissociation albumino-cytologique au LCR)." },
  { id: 'hemorragie-meningee', nom: 'Hémorragie méningée', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['céphalées', 'raideur de nuque', 'vomissements', 'troubles de conscience', 'céphalée brutale', 'photophobie'],
    orientation: "Céphalée brutale en coup de tonnerre avec syndrome méningé sans fièvre = hémorragie méningée : TDM cérébrale sans injection en urgence (PL si TDM normale)." },
  { id: 'myasthenie', nom: 'Myasthénie', discipline: 'Neurologie', chapter: 'iv-53-affections-neurologiques',
    cles: ['fatigabilité musculaire', 'ptosis', 'diplopie', 'femme jeune', 'troubles de la déglutition', 'déficit moteur'],
    orientation: "Faiblesse musculaire fluctuante aggravée à l'effort et en fin de journée (ptosis, diplopie, troubles de déglutition) = myasthénie (anticorps anti-récepteurs de l'acétylcholine)." },
];
