// @ts-nocheck
// Pathologies du domaine — voir lexique.js pour le format.
export const pathologies = [
  { id: 'anemie-inflammatoire', nom: 'Anémie inflammatoire', discipline: 'Hématologie', chapter: 'hemato-anemies',
    cles: ['anémie', 'microcytose', 'asthénie', 'pâleur', 'fer sérique bas', 'ferritine augmentée', 'syndrome inflammatoire'],
    orientation: "Anémie modérée normo- ou microcytaire avec fer sérique bas mais ferritine normale ou élevée et CRP augmentée : anémie inflammatoire, à distinguer de la carence martiale (ferritine effondrée)." },
  { id: 'anemie-hemolytique-auto-immune', nom: 'Anémie hémolytique auto-immune (AHAI)', discipline: 'Hématologie', chapter: 'hemato-anemies',
    cles: ['anémie', 'hémolyse', 'ictère', 'splénomégalie', 'asthénie', 'macrocytose', 'test de Coombs direct positif'],
    orientation: "Anémie régénérative avec hémolyse (haptoglobine effondrée, LDH et bilirubine libre élevées) et test de Coombs direct positif = AHAI ; rechercher lymphome, lupus ou médicament inducteur." },
  { id: 'thalassemie', nom: 'Thalassémie', discipline: 'Hématologie', chapter: 'iv-26-hemoglobinopathies',
    cles: ['anémie', 'microcytose', 'hémolyse', 'splénomégalie', 'antécédents familiaux', 'origine africaine', 'électrophorèse de l\'hémoglobine anormale'],
    orientation: "Microcytose franche sans carence martiale (ferritine normale) dans un contexte familial et d'origine méditerranéenne ou africaine : évoquer une thalassémie, confirmée par l'électrophorèse de l'hémoglobine." },
  { id: 'thrombopenie-immunologique-pti', nom: 'Purpura thrombopénique immunologique (PTI)', discipline: 'Hématologie', chapter: 'iv-31-thrombopenies',
    cles: ['thrombopénie', 'purpura', 'hémorragies', 'sujet jeune', 'thrombopénie isolée', 'moelle riche en mégacaryocytes'],
    orientation: "Thrombopénie profonde isolée (reste de l'hémogramme normal) avec purpura, souvent après épisode viral chez un sujet jeune : PTI, diagnostic d'élimination." },
  { id: 'thrombopenie-induite-heparine-tih', nom: 'Thrombopénie induite par l\'héparine (TIH)', discipline: 'Hématologie', chapter: 'iv-31-thrombopenies',
    cles: ['thrombopénie', 'héparine', 'thrombose', 'chute des plaquettes', 'anticorps anti-PF4', 'terrain post-opératoire'],
    orientation: "Chute des plaquettes de plus de 40 % entre J5 et J10 d'un traitement par héparine, avec thromboses paradoxales : TIH de type II (immuno-allergique) ; arrêt immédiat de l'héparine." },
  { id: 'agranulocytose-medicamenteuse', nom: 'Agranulocytose médicamenteuse', discipline: 'Hématologie', chapter: 'iv-30-cytopenies-medicamenteuses',
    cles: ['fièvre', 'asthénie', 'angine', 'neutropénie', 'prise médicamenteuse', 'agranulocytose'],
    orientation: "Fièvre avec angine ou infection sévère et polynucléaires neutrophiles effondrés (< 0,5 G/L) après introduction d'un médicament (antithyroïdien, neuroleptique, sulfamide) : agranulocytose médicamenteuse, urgence." },
  { id: 'lymphome-hodgkin', nom: 'Lymphome de Hodgkin', discipline: 'Hématologie', chapter: 'iv-29-hyperlymphocytoses',
    cles: ['adénopathies', 'prurit', 'sueurs nocturnes', 'amaigrissement', 'fièvre', 'sujet jeune', 'adénopathie cervicale'],
    orientation: "Adénopathies sus-diaphragmatiques indolores chez un sujet jeune avec signes généraux (fièvre, sueurs nocturnes, amaigrissement) et prurit : lymphome de Hodgkin ; biopsie ganglionnaire (cellules de Reed-Sternberg)." },
  { id: 'lymphome-non-hodgkinien', nom: 'Lymphome non hodgkinien', discipline: 'Hématologie', chapter: 'iv-29-hyperlymphocytoses',
    cles: ['adénopathies', 'splénomégalie', 'amaigrissement', 'sueurs nocturnes', 'fièvre', 'sujet âgé', 'hyperlymphocytose'],
    orientation: "Adénopathies multiples avec ou sans splénomégalie et signes généraux chez un sujet plus âgé, parfois avec passage sanguin (hyperlymphocytose) : lymphome non hodgkinien ; immunophénotypage et biopsie précisent le type." },
  { id: 'maladie-willebrand', nom: 'Maladie de Willebrand', discipline: 'Hématologie', chapter: 'iv-25-hemophilies-willebrand',
    cles: ['hémorragies', 'épistaxis', 'ménorragies', 'antécédents familiaux', 'TCA allongé', 'temps de saignement allongé'],
    orientation: "Saignements muqueux (épistaxis, ménorragies, gingivorragies) à transmission familiale, avec TCA parfois allongé et allongement du temps d'occlusion : maladie de Willebrand, anomalie constitutionnelle de l'hémostase la plus fréquente." },
  { id: 'thrombocytemie-essentielle', nom: 'Thrombocytémie essentielle', discipline: 'Hématologie',
    cles: ['thrombocytose', 'thrombose', 'splénomégalie', 'sujet âgé', 'érythromélalgie', 'mutation JAK2'],
    orientation: "Thrombocytose importante et persistante (> 450 G/L) sans cause réactionnelle, avec thromboses ou érythromélalgie : thrombocytémie essentielle, syndrome myéloprolifératif souvent lié à la mutation JAK2." },
  { id: 'myelofibrose-primitive', nom: 'Myélofibrose primitive', discipline: 'Hématologie',
    cles: ['splénomégalie', 'asthénie', 'amaigrissement', 'anémie', 'myélémie', 'schizocytes', 'sujet âgé'],
    orientation: "Splénomégalie souvent volumineuse avec anémie et tableau leuco-érythroblastique (myélémie, érythroblastes, hématies en larme) : myélofibrose primitive ; la ponction médullaire est souvent blanche (moelle fibreuse)." },
  { id: 'syndrome-myelodysplasique', nom: 'Syndrome myélodysplasique', discipline: 'Hématologie', chapter: 'iv-28-leucemies-aigues-smd',
    cles: ['anémie', 'macrocytose', 'asthénie', 'pâleur', 'thrombopénie', 'neutropénie', 'sujet âgé'],
    orientation: "Cytopénie(s) chronique(s), souvent anémie macrocytaire arégénérative, chez un sujet âgé, avec moelle riche et signes de dysmyélopoïèse : syndrome myélodysplasique, à risque de transformation en leucémie aiguë." },
  { id: 'gammapathie-monoclonale-mgus', nom: 'Gammapathie monoclonale de signification indéterminée (MGUS)', discipline: 'Hématologie', chapter: 'iv-27-myelome-dysglobulinemies',
    cles: ['pic monoclonal', 'sujet âgé', 'immunoglobuline monoclonale', 'découverte fortuite', 'absence de signe CRAB'],
    orientation: "Pic monoclonal de faible abondance (< 30 g/L) sans hypercalcémie, insuffisance rénale, anémie ni lésion osseuse (pas de critère CRAB) : MGUS ; surveillance car risque d'évolution vers un myélome." },
  { id: 'maladie-waldenstrom', nom: 'Maladie de Waldenström', discipline: 'Hématologie', chapter: 'iv-27-myelome-dysglobulinemies',
    cles: ['pic monoclonal', 'adénopathies', 'splénomégalie', 'asthénie', 'anémie', 'sujet âgé', 'syndrome d\'hyperviscosité'],
    orientation: "Pic monoclonal de type IgM avec syndrome tumoral (adénopathies, splénomégalie) et signes d'hyperviscosité (troubles visuels, neurologiques) : maladie de Waldenström (lymphome lymphoplasmocytaire)." },
  { id: 'polyglobulie-secondaire', nom: 'Polyglobulie secondaire', discipline: 'Hématologie', chapter: 'iv-23-polyglobulies',
    cles: ['polyglobulie', 'sujet âgé', 'tabagisme', 'hypoxie chronique', 'érythropoïétine augmentée', 'cyanose'],
    orientation: "Élévation isolée de l'hématocrite avec EPO élevée dans un contexte d'hypoxie chronique (BPCO, tabac, apnées du sommeil, altitude) : polyglobulie secondaire réactionnelle, à distinguer de la maladie de Vaquez (EPO basse, JAK2 muté)." },
  { id: 'syndrome-mononucleosique', nom: 'Syndrome mononucléosique (MNI)', discipline: 'Hématologie', chapter: 'iv-29-hyperlymphocytoses',
    cles: ['fièvre', 'adénopathies', 'angine', 'splénomégalie', 'asthénie', 'hyperlymphocytose', 'sujet jeune'],
    orientation: "Sujet jeune avec fièvre, angine, adénopathies et splénomégalie, et hyperlymphocytose faite de grands lymphocytes hyperbasophiles : syndrome mononucléosique (EBV le plus souvent) ; MNI-test et sérologie." },
  { id: 'hypereosinophilie', nom: 'Hyperéosinophilie (orientation étiologique)', discipline: 'Hématologie',
    cles: ['hyperéosinophilie', 'prurit', 'éruption', 'terrain allergique', 'asthme', 'retour de voyage'],
    orientation: "Éosinophilie franche et persistante : évoquer d'abord une cause parasitaire (helminthose), allergique ou médicamenteuse avant un syndrome hyperéosinophilique clonal ; interrogatoire et courbe de Lavier orientent." },
  { id: 'anaphylaxie', nom: 'Anaphylaxie', discipline: 'Immunologie', chapter: 'iv-32-asthme-allergies',
    cles: ['éruption', 'prurit', 'urticaire', 'hypotension', 'malaise', 'terrain allergique'],
    orientation: "Apparition brutale, après contact allergénique (médicament, aliment, piqûre), d'une urticaire avec œdème, bronchospasme et collapsus : choc anaphylactique (hypersensibilité de type I) ; adrénaline IM immédiate." },
  { id: 'oedeme-quincke', nom: 'Œdème de Quincke (angio-œdème)', discipline: 'Immunologie', chapter: 'iv-32-asthme-allergies',
    cles: ['éruption', 'prurit', 'œdème du visage', 'gêne respiratoire', 'urticaire', 'terrain allergique'],
    orientation: "Œdème sous-cutané et muqueux du visage, des lèvres et de la glotte, souvent associé à une urticaire : œdème de Quincke ; risque d'asphyxie si atteinte laryngée (dyspnée, dysphonie), urgence." },
  { id: 'polyarthrite-rhumatoide', nom: 'Polyarthrite rhumatoïde', discipline: 'Immunologie', chapter: 'iv-33-maladies-auto-immunes',
    cles: ['arthralgies', 'raideur matinale', 'arthrite symétrique', 'facteur rhumatoïde', 'anticorps anti-CCP', 'syndrome inflammatoire'],
    orientation: "Polyarthrite bilatérale et symétrique des petites articulations avec raideur matinale prolongée et syndrome inflammatoire : polyarthrite rhumatoïde ; les anticorps anti-CCP sont très spécifiques." },
  { id: 'deficit-immunitaire-combine-severe', nom: 'Déficit immunitaire combiné sévère (DICS)', discipline: 'Immunologie', chapter: 'iv-34-deficits-immunitaires-congenitaux',
    cles: ['fièvre', 'garçon', 'infections répétées', 'infections opportunistes', 'retard staturo-pondéral', 'terrain immunodéprimé'],
    orientation: "Nourrisson (souvent un garçon) présentant des infections sévères, répétées et opportunistes (virus, champignons) dès les premiers mois avec cassure staturo-pondérale : déficit immunitaire combiné sévère, urgence (greffe de cellules souches)." },
  { id: 'deficit-immunitaire-commun-variable', nom: 'Déficit immunitaire commun variable (DICV)', discipline: 'Immunologie', chapter: 'iv-34-deficits-immunitaires-congenitaux',
    cles: ['infections répétées', 'sujet jeune', 'infections ORL', 'diarrhée chronique', 'hypogammaglobulinémie', 'terrain immunodéprimé'],
    orientation: "Adulte jeune avec infections bactériennes ORL et bronchopulmonaires à répétition (bactéries encapsulées) et hypogammaglobulinémie : déficit immunitaire commun variable, déficit primitif symptomatique le plus fréquent de l'adulte." },
];
