// @ts-nocheck
// Pathologies du domaine — voir lexique.js pour le format.
export const pathologies = [
  // ─── Infections du SNC ───
  { id: 'encephalite-herpetique', nom: 'Encéphalite herpétique (HSV)', discipline: 'Infectiologie', chapter: 'iv-1-infections-snc',
    cles: ['fièvre', 'céphalées', 'troubles de conscience', 'convulsions', 'troubles du comportement', 'aphasie'],
    orientation: "Fièvre + troubles de conscience/comportement + signes focaux temporaux = encéphalite herpétique : aciclovir IV en URGENCE avant même la PCR HSV du LCR." },
  { id: 'meningite-virale', nom: 'Méningite virale (lymphocytaire)', discipline: 'Infectiologie', chapter: 'iv-1-infections-snc',
    cles: ['fièvre', 'céphalées', 'raideur de nuque', 'photophobie', 'syndrome méningé', 'LCR clair'],
    orientation: "Syndrome méningé fébrile avec LCR clair lymphocytaire normoglycorachique = méningite virale (entérovirus) : évolution bénigne, traitement symptomatique." },
  { id: 'abces-cerebral', nom: 'Abcès cérébral', discipline: 'Infectiologie', chapter: 'iv-1-infections-snc',
    cles: ['fièvre', 'céphalées', 'troubles de conscience', 'convulsions', 'signes focaux', 'porte d\'entrée ORL'],
    orientation: "Fièvre + céphalées + signes de localisation ± crises = abcès cérébral : imagerie (prise de contraste annulaire) ; chercher une porte d'entrée ORL ou dentaire." },

  // ─── Bactériémies / endocardites / infections profondes ───
  { id: 'sepsis-choc-septique', nom: 'Sepsis / choc septique', discipline: 'Infectiologie', chapter: 'iv-2-bacteriemies-endocardites',
    cles: ['fièvre', 'frissons', 'hypotension', 'tachycardie', 'troubles de conscience', 'hémocultures positives', 'marbrures'],
    orientation: "Infection + défaillance d'organe (qSOFA) ± hypotension réfractaire = sepsis/choc septique : hémocultures, antibiothérapie et remplissage dès la 1re heure." },
  { id: 'bacteriemie-staphylocoque', nom: 'Bactériémie à Staphylococcus aureus', discipline: 'Infectiologie', chapter: 'iv-2-bacteriemies-endocardites',
    cles: ['fièvre', 'frissons', 'hémocultures positives', 'porte d\'entrée cutanée', 'cathéter', 'sepsis'],
    orientation: "Hémocultures positives à S. aureus = jamais banal : rechercher la porte d'entrée et les localisations secondaires (endocardite, spondylodiscite) ; écho cœur." },
  { id: 'osteomyelite-spondylodiscite', nom: 'Ostéomyélite / spondylodiscite', discipline: 'Infectiologie', chapter: 'iv-2-bacteriemies-endocardites',
    cles: ['fièvre', 'douleur osseuse', 'douleur lombaire', 'raideur rachidienne', 'hémocultures positives', 'syndrome inflammatoire'],
    orientation: "Douleur osseuse ou rachidienne fébrile inflammatoire + syndrome inflammatoire = ostéomyélite/spondylodiscite : IRM, hémocultures, biopsie disco-vertébrale." },
  { id: 'arthrite-septique', nom: 'Arthrite septique', discipline: 'Infectiologie',
    cles: ['fièvre', 'monoarthrite', 'douleur articulaire', 'impotence fonctionnelle', 'épanchement articulaire', 'hyperleucocytose'],
    orientation: "Monoarthrite aiguë fébrile, chaude et impotente = arthrite septique jusqu'à preuve du contraire : ponction articulaire en URGENCE avant toute antibiothérapie." },
  { id: 'erysipele', nom: 'Érysipèle (dermohypodermite bactérienne)', discipline: 'Infectiologie',
    cles: ['fièvre', 'frissons', 'placard inflammatoire', 'porte d\'entrée', 'adénopathies', 'hyperleucocytose'],
    orientation: "Grosse jambe rouge aiguë fébrile unilatérale + porte d'entrée = érysipèle (streptocoque) : amoxicilline ; guetter les signes de fasciite nécrosante." },
  { id: 'fasciite-necrosante', nom: 'Fasciite nécrosante (dermohypodermite nécrosante)', discipline: 'Infectiologie',
    cles: ['fièvre', 'douleur intense', 'placard inflammatoire', 'nécrose cutanée', 'sepsis', 'crépitation sous-cutanée'],
    orientation: "Douleur disproportionnée + signes généraux sévères + nécrose/crépitation = fasciite nécrosante : urgence chirurgicale (débridement) + antibiothérapie." },

  // ─── Infections urinaires ───
  { id: 'prostatite-aigue', nom: 'Prostatite aiguë', discipline: 'Infectiologie', chapter: 'iv-3-infections-urinaires',
    cles: ['fièvre', 'frissons', 'brûlures mictionnelles', 'pollakiurie', 'dysurie', 'douleur pelvienne', 'toucher rectal douloureux'],
    orientation: "Homme : fièvre + signes urinaires + prostate douloureuse au TR = prostatite aiguë : ECBU, antibiothérapie prolongée à bonne diffusion (fluoroquinolone/C3G)." },

  // ─── Infections digestives ───
  { id: 'fievre-typhoide', nom: 'Fièvre typhoïde', discipline: 'Infectiologie', chapter: 'iv-4-infections-digestives',
    cles: ['fièvre', 'retour de voyage', 'douleur abdominale', 'diarrhée', 'céphalées', 'dissociation pouls-température', 'hémocultures positives'],
    orientation: "Fièvre en plateau au retour d'une zone d'endémie + troubles digestifs + tuphos = typhoïde (Salmonella Typhi) : hémocultures, céphalosporine de 3e génération." },
  { id: 'angiocholite', nom: 'Angiocholite aiguë', discipline: 'Infectiologie', chapter: 'iv-4-infections-digestives',
    cles: ['fièvre', 'frissons', 'ictère', 'douleur abdominale', 'hémocultures positives', 'obstacle biliaire'],
    orientation: "Triade de Charcot (douleur de l'hypochondre droit + fièvre + ictère) = angiocholite : urgence, hémocultures, antibiothérapie + drainage biliaire." },

  // ─── Infections ORL / respiratoires ───
  { id: 'sinusite-aigue', nom: 'Sinusite maxillaire aiguë', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['fièvre', 'céphalées', 'douleur faciale', 'rhinorrhée purulente', 'obstruction nasale'],
    orientation: "Douleur faciale unilatérale majorée en antéflexion + rhinorrhée purulente au décours d'un rhume = sinusite maxillaire ; amoxicilline si bactérienne documentée." },
  { id: 'otite-moyenne-aigue', nom: 'Otite moyenne aiguë', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['fièvre', 'otalgie', 'otorrhée', 'hypoacousie', 'enfant', 'rhinopharyngite'],
    orientation: "Enfant : otalgie fébrile + tympan bombé inflammatoire à l'otoscopie = OMA purulente ; amoxicilline (pneumocoque, Haemophilus)." },
  { id: 'coqueluche', nom: 'Coqueluche', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['toux', 'toux quinteuse', 'apyrexie', 'nourrisson', 'contage', 'reprise inspiratoire'],
    orientation: "Toux quinteuse prolongée avec chant du coq ou apnées (nourrisson) sans fièvre = coqueluche (Bordetella) : PCR, macrolides, vacciner l'entourage." },
  { id: 'bronchiolite', nom: 'Bronchiolite aiguë du nourrisson', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['toux', 'dyspnée', 'nourrisson', 'sibilants', 'rhinorrhée', 'difficultés alimentaires'],
    orientation: "Nourrisson < 2 ans : rhinite puis dyspnée expiratoire avec sibilants et freinage = bronchiolite (VRS) : prise en charge surtout symptomatique." },
  { id: 'bronchite-aigue', nom: 'Bronchite aiguë', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['toux', 'fièvre', 'expectoration', 'douleur thoracique', 'contage', 'apyrexie'],
    orientation: "Toux fébrile modérée sans foyer auscultatoire = bronchite aiguë le plus souvent virale : pas d'antibiotiques en l'absence de comorbidité." },
  { id: 'diphterie', nom: 'Diphtérie', discipline: 'Infectiologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['angine', 'fausses membranes', 'fièvre', 'dysphagie', 'absence de vaccination', 'adénopathies'],
    orientation: "Angine à fausses membranes extensives et adhérentes chez un sujet non vacciné = diphtérie : sérothérapie antitoxine en urgence + antibiotiques." },
  { id: 'covid-19', nom: 'COVID-19 (SARS-CoV-2)', discipline: 'Virologie', chapter: 'iv-5-infections-orl-respiratoires',
    cles: ['fièvre', 'toux', 'dyspnée', 'anosmie', 'agueusie', 'asthénie', 'contage'],
    orientation: "Fièvre + toux + anosmie/agueusie en contexte épidémique = COVID-19 : test PCR/antigénique ; surveiller la SpO2 (formes hypoxémiantes retardées)." },

  // ─── IST ───
  { id: 'uretrite-gonococcique', nom: 'Urétrite gonococcique (gonorrhée)', discipline: 'Infectiologie', chapter: 'iv-6-ist',
    cles: ['écoulement urétral', 'brûlures mictionnelles', 'dysurie', 'comportement à risque', 'homme'],
    orientation: "Écoulement urétral purulent + brûlures après un rapport à risque = urétrite à gonocoque : PCR, ceftriaxone (+ couvrir Chlamydia), dépister le partenaire." },
  { id: 'chlamydiose', nom: 'Infection à Chlamydia trachomatis', discipline: 'Infectiologie', chapter: 'iv-6-ist',
    cles: ['écoulement urétral', 'brûlures mictionnelles', 'leucorrhées', 'douleur pelvienne', 'comportement à risque', 'asymptomatique'],
    orientation: "IST la plus fréquente, souvent asymptomatique : urétrite/cervicite subaiguë, risque de salpingite et de stérilité ; PCR, azithromycine ou doxycycline." },
  { id: 'herpes-genital', nom: 'Herpès génital', discipline: 'Infectiologie', chapter: 'iv-6-ist',
    cles: ['vésicules génitales', 'ulcérations génitales', 'douleur génitale', 'adénopathies', 'comportement à risque', 'récidive'],
    orientation: "Vésicules puis ulcérations génitales douloureuses et récidivantes = herpès (HSV-2) : PCR, aciclovir ; risque néonatal grave en fin de grossesse." },

  // ─── Infections et grossesse ───
  { id: 'listeriose', nom: 'Listériose', discipline: 'Infectiologie', chapter: 'iv-7-infections-grossesse',
    cles: ['fièvre', 'grossesse', 'terrain immunodéprimé', 'sujet âgé', 'troubles de conscience', 'raideur de nuque', 'syndrome grippal'],
    orientation: "Fièvre chez la femme enceinte, l'immunodéprimé ou le sujet âgé, ± atteinte neuroméningée = listériose : hémocultures, amoxicilline (Listeria résistante aux C3G)." },
  { id: 'infection-urinaire-grossesse', nom: 'Infection urinaire gravidique', discipline: 'Infectiologie', chapter: 'iv-7-infections-grossesse',
    cles: ['grossesse', 'brûlures mictionnelles', 'pollakiurie', 'fièvre', 'douleur lombaire', 'bandelette urinaire positive'],
    orientation: "Toute bactériurie de la femme enceinte doit être traitée (risque de pyélonéphrite et d'accouchement prématuré) : ECBU systématique, antibiotiques adaptés." },

  // ─── Hépatites virales ───
  { id: 'hepatite-b-chronique', nom: 'Hépatite B chronique', discipline: 'Virologie', chapter: 'iv-8-hepatites-virales',
    cles: ['asthénie', 'cytolyse', 'ictère', 'comportement à risque', 'portage chronique', 'antigène HBs'],
    orientation: "AgHBs persistant plus de 6 mois = hépatite B chronique : évaluer réplication (ADN VHB, AgHBe) et fibrose ; risque de cirrhose/CHC ; analogues nucléos(t)idiques." },
  { id: 'hepatite-c-chronique', nom: 'Hépatite C chronique', discipline: 'Virologie', chapter: 'iv-8-hepatites-virales',
    cles: ['asthénie', 'cytolyse', 'comportement à risque', 'portage chronique', 'toxicomanie intraveineuse', 'découverte fortuite'],
    orientation: "Souvent asymptomatique, découverte sur une cytolyse ou un facteur de risque : sérologie + ARN VHC ; guérison quasi constante sous antiviraux d'action directe." },

  // ─── Immunodéprimé / VIH ───
  { id: 'sida-infections-opportunistes', nom: 'SIDA (infections opportunistes)', discipline: 'Infectiologie', chapter: 'iv-9-immunodeprime',
    cles: ['fièvre', 'amaigrissement', 'terrain immunodéprimé', 'diarrhée', 'toux', 'adénopathies', 'candidose buccale'],
    orientation: "VIH évolué (CD4 bas) : penser pneumocystose, toxoplasmose cérébrale, tuberculose, CMV ; adapter les prophylaxies au taux de CD4." },
  { id: 'pneumocystose', nom: 'Pneumocystose pulmonaire', discipline: 'Infectiologie', chapter: 'iv-9-immunodeprime',
    cles: ['fièvre', 'dyspnée', 'toux', 'terrain immunodéprimé', 'hypoxémie', 'VIH'],
    orientation: "Immunodéprimé (VIH avec CD4 < 200) : dyspnée fébrile d'aggravation progressive + hypoxémie + verre dépoli = pneumocystose : cotrimoxazole, LBA." },
  { id: 'cmv-immunodeprime', nom: 'Maladie à CMV de l\'immunodéprimé', discipline: 'Virologie', chapter: 'iv-9-immunodeprime',
    cles: ['fièvre', 'terrain immunodéprimé', 'troubles visuels', 'diarrhée', 'cytolyse', 'greffe'],
    orientation: "Greffé ou VIH : fièvre + atteinte d'organe (rétinite, colite, pneumonie) = maladie à CMV : PCR CMV (antigénémie), ganciclovir." },
  { id: 'neutropenie-febrile', nom: 'Neutropénie fébrile', discipline: 'Infectiologie', chapter: 'iv-9-immunodeprime',
    cles: ['fièvre', 'terrain immunodéprimé', 'neutropénie', 'frissons', 'sepsis', 'chimiothérapie'],
    orientation: "Fièvre + PNN < 500/mm³ (aplasie post-chimiothérapie) = urgence : hémocultures et antibiothérapie à large spectre anti-pyocyanique dans l'heure." },

  // ─── Résistance aux anti-infectieux ───
  { id: 'infection-bmr', nom: 'Infection à bactérie multirésistante (BMR/BHRe)', discipline: 'Infectiologie', chapter: 'iv-11-resistance-anti-infectieux',
    cles: ['fièvre', 'antibiotique récent', 'hospitalisation', 'portage', 'sepsis', 'échec thérapeutique'],
    orientation: "Infection résistante au traitement usuel sur terrain à risque (antibiothérapies/hospitalisations répétées, voyage) = BMR : antibiogramme, adaptation, isolement." },
  { id: 'sarm', nom: 'Infection à SARM (S. aureus résistant à la méticilline)', discipline: 'Infectiologie', chapter: 'iv-11-resistance-anti-infectieux',
    cles: ['fièvre', 'porte d\'entrée cutanée', 'hémocultures positives', 'antibiotique récent', 'hospitalisation', 'sepsis'],
    orientation: "Infection à S. aureus résistant à la méticilline (contexte de soins) : documenter par l'antibiogramme ; glycopeptides ou alternatives, mesures d'hygiène." },

  // ─── Maladies infectieuses à prévention vaccinale / toxines ───
  { id: 'tetanos', nom: 'Tétanos', discipline: 'Infectiologie',
    cles: ['trismus', 'contractures musculaires', 'plaie souillée', 'absence de vaccination', 'spasmes', 'dysphagie'],
    orientation: "Trismus + contractures généralisées après une plaie chez un sujet non à jour de vaccin = tétanos : urgence, immunoglobulines, métronidazole, réanimation." },
  { id: 'botulisme', nom: 'Botulisme', discipline: 'Infectiologie',
    cles: ['diplopie', 'dysphagie', 'paralysie descendante', 'sécheresse buccale', 'apyrexie', 'conserves artisanales'],
    orientation: "Troubles oculaires (diplopie, mydriase) + dysphagie + paralysie descendante symétrique après conserves familiales = botulisme : sérothérapie, réanimation." },
  { id: 'rougeole', nom: 'Rougeole', discipline: 'Virologie',
    cles: ['fièvre', 'éruption', 'toux', 'conjonctivite', 'signe de Koplik', 'contage'],
    orientation: "Fièvre + catarrhe oculo-respiratoire + signe de Koplik puis éruption maculopapuleuse descendante = rougeole ; maladie à déclaration obligatoire, vacciner." },
  { id: 'oreillons', nom: 'Oreillons', discipline: 'Virologie',
    cles: ['fièvre', 'tuméfaction parotidienne', 'douleur', 'contage', 'orchite', 'céphalées'],
    orientation: "Parotidite bilatérale fébrile de l'enfant ou de l'adulte jeune non vacciné = oreillons (ourlien) ; complications : orchite, méningite, pancréatite." },
  { id: 'varicelle', nom: 'Varicelle', discipline: 'Virologie',
    cles: ['fièvre', 'éruption', 'vésicules', 'prurit', 'contage', 'éruption polymorphe'],
    orientation: "Éruption vésiculeuse prurigineuse d'éléments d'âges différents (VZV) + fièvre modérée = varicelle ; formes graves chez l'immunodéprimé, la femme enceinte, le nouveau-né." },
  { id: 'zona', nom: 'Zona', discipline: 'Virologie',
    cles: ['éruption', 'vésicules', 'douleur', 'éruption métamérique', 'terrain immunodéprimé', 'sujet âgé'],
    orientation: "Éruption vésiculeuse douloureuse unilatérale limitée à un dermatome = zona (réactivation du VZV) : valaciclovir précoce (risque de douleurs post-zostériennes)." },
  { id: 'impetigo', nom: 'Impétigo', discipline: 'Infectiologie',
    cles: ['éruption', 'lésions croûteuses', 'croûtes mélicériques', 'prurit', 'enfant', 'contagieux'],
    orientation: "Lésions vésiculo-croûteuses mélicériques du visage chez l'enfant = impétigo (staphylocoque/streptocoque), très contagieux : antibiothérapie locale ou générale." },
];
