// @ts-nocheck
// Pathologies du domaine — voir lexique.js pour le format.
export const pathologies = [
  { id: 'intoxication-paracetamol', nom: 'Intoxication au paracétamol', discipline: 'Toxicologie', chapter: 'v-47-toxicologie-antalgiques',
    cles: ['ingestion volontaire', 'vomissements', 'douleur abdominale', 'cytolyse', 'ictère', 'insuffisance hépatique'],
    orientation: "Ingestion massive + cytolyse retardée (H24-72) = intoxication au paracétamol : dosage plasmatique reporté sur le nomogramme de Rumack-Matthew, antidote N-acétylcystéine." },
  { id: 'intoxication-salicyles', nom: 'Intoxication aux salicylés (aspirine)', discipline: 'Toxicologie', chapter: 'v-47-toxicologie-antalgiques',
    cles: ['ingestion volontaire', 'vomissements', 'hyperthermie', 'sueurs', 'acidose métabolique', 'acouphènes', 'polypnée'],
    orientation: "Vomissements + polypnée + acouphènes + acidose métabolique avec alcalose respiratoire = intoxication salicylée : alcalinisation des urines, épuration extrarénale si forme sévère." },
  { id: 'intoxication-digoxine', nom: 'Intoxication à la digoxine (digitaliques)', discipline: 'Toxicologie', chapter: 'v-48-cardiotoxiques',
    cles: ['vomissements', 'bradycardie', 'hyperkaliémie', 'troubles visuels', 'troubles du rythme', 'douleur abdominale'],
    orientation: "Bradycardie + troubles digestifs + dyschromatopsie + hyperkaliémie = intoxication digitalique : anticorps antidigoxine (fragments Fab) si signes de gravité." },
  { id: 'intoxication-lithium', nom: 'Intoxication au lithium', discipline: 'Toxicologie', chapter: 'v-46-toxicologie-psychotropes',
    cles: ['troubles de conscience', 'tremblements', 'convulsions', 'vomissements', 'ataxie', 'confusion'],
    orientation: "Tremblements + ataxie + confusion chez un patient bipolaire = intoxication au lithium : lithémie, réhydratation, hémodialyse si forme sévère (pas d'antidote spécifique)." },
  { id: 'intoxication-benzodiazepines', nom: 'Intoxication aux benzodiazépines', discipline: 'Toxicologie', chapter: 'v-46-toxicologie-psychotropes',
    cles: ['ingestion volontaire', 'troubles de conscience', 'coma', 'dépression respiratoire', 'hypotonie', 'somnolence'],
    orientation: "Coma calme hypotonique peu profond avec dépression respiratoire modérée = intoxication aux benzodiazépines : antidote flumazénil (prudence si co-ingestion de convulsivants)." },
  { id: 'overdose-opiaces', nom: 'Overdose aux opiacés', discipline: 'Toxicologie', chapter: 'iii-16-toxicomanies',
    cles: ['comportement à risque', 'myosis', 'coma', 'dépression respiratoire', 'troubles de conscience', 'cyanose'],
    orientation: "Triade myosis serré + coma + dépression respiratoire = overdose aux opiacés : antidote naloxone en titration et ventilation." },
  { id: 'intoxication-cocaine', nom: 'Intoxication à la cocaïne', discipline: 'Toxicologie', chapter: 'iii-16-toxicomanies',
    cles: ['comportement à risque', 'agitation', 'mydriase', 'tachycardie', 'hyperthermie', 'convulsions', 'douleur thoracique'],
    orientation: "Syndrome sympathomimétique (agitation, mydriase, tachycardie, hyperthermie) + douleur thoracique = intoxication à la cocaïne : benzodiazépines, éviter un bêta-bloquant isolé." },
  { id: 'intoxication-amphetamines', nom: 'Intoxication aux amphétamines (ecstasy/MDMA)', discipline: 'Toxicologie', chapter: 'iii-16-toxicomanies',
    cles: ['comportement à risque', 'agitation', 'mydriase', 'tachycardie', 'hyperthermie', 'sueurs', 'convulsions'],
    orientation: "Syndrome sympathomimétique avec hyperthermie sévère en contexte festif = intoxication aux amphétamines : refroidissement actif, benzodiazépines, hydratation (risque d'hyponatrémie)." },
  { id: 'intoxication-cannabis', nom: 'Intoxication au cannabis', discipline: 'Toxicologie', chapter: 'iii-16-toxicomanies',
    cles: ['comportement à risque', 'tachycardie', 'agitation', 'somnolence', 'conjonctives injectées', 'ataxie'],
    orientation: "Euphorie ou somnolence + tachycardie + conjonctives rouges = intoxication au cannabis : surveillance et traitement symptomatique (coma possible chez le jeune enfant)." },
  { id: 'intoxication-methanol', nom: 'Intoxication au méthanol', discipline: 'Toxicologie', chapter: 'iii-11-toxicologie-alcools',
    cles: ['ingestion volontaire', 'troubles visuels', 'acidose métabolique', 'troubles de conscience', 'coma', 'céphalées'],
    orientation: "Intervalle libre puis acidose métabolique à trou anionique élevé + troubles visuels (cécité) = intoxication au méthanol : fomépizole (ou éthanol), épuration extrarénale." },
  { id: 'intoxication-ethylene-glycol', nom: 'Intoxication à l\'éthylène-glycol', discipline: 'Toxicologie', chapter: 'iii-11-toxicologie-alcools',
    cles: ['ingestion volontaire', 'acidose métabolique', 'troubles de conscience', 'coma', 'insuffisance rénale', 'convulsions'],
    orientation: "Ivresse apparente + acidose métabolique à trou anionique + cristaux d'oxalate de calcium + insuffisance rénale = intoxication à l'éthylène-glycol : fomépizole (ou éthanol), dialyse." },
  { id: 'intoxication-ethanol-aigu', nom: 'Intoxication éthylique aiguë', discipline: 'Toxicologie', chapter: 'iii-11-toxicologie-alcools',
    cles: ['alcool', 'troubles de conscience', 'coma', 'ataxie', 'vomissements', 'hypoglycémie'],
    orientation: "Ivresse aiguë avec ataxie, coma hypotonique et hypoglycémie = intoxication éthylique aiguë : surveillance, resucrage, protection des voies aériennes (pas d'antidote)." },
  { id: 'intoxication-organophosphores', nom: 'Intoxication aux organophosphorés', discipline: 'Toxicologie', chapter: 'iii-13-produits-phytosanitaires',
    cles: ['ingestion volontaire', 'myosis', 'sueurs', 'bradycardie', 'convulsions', 'coma', 'dépression respiratoire'],
    orientation: "Syndrome cholinergique (myosis, hypersécrétions, bradycardie, fasciculations) = intoxication aux organophosphorés : atropine + pralidoxime." },
  { id: 'saturnisme-plomb', nom: 'Saturnisme (intoxication au plomb)', discipline: 'Toxicologie', chapter: 'iii-14-poisons-hemoglobine',
    cles: ['douleur abdominale', 'anémie', 'céphalées', 'constipation', 'liseré gingival', 'troubles de conscience'],
    orientation: "Coliques de plomb + anémie + encéphalopathie chez un enfant en habitat ancien = saturnisme : plombémie, chélateurs (EDTA calcique, DMSA)." },
  { id: 'methemoglobinemie', nom: 'Méthémoglobinémie', discipline: 'Toxicologie', chapter: 'iii-14-poisons-hemoglobine',
    cles: ['cyanose', 'céphalées', 'dyspnée', 'troubles de conscience', 'coma', 'tachycardie'],
    orientation: "Cyanose grise résistante à l'oxygène + sang couleur chocolat + SpO2 discordante = méthémoglobinémie (agents oxydants) : antidote bleu de méthylène." },
  { id: 'intoxication-champignons-phalloidien', nom: 'Intoxication par les champignons (syndrome phalloïdien)', discipline: 'Toxicologie',
    cles: ['vomissements', 'douleur abdominale', 'cytolyse', 'ictère', 'diarrhée', 'insuffisance hépatique'],
    orientation: "Intervalle > 6 h puis gastro-entérite sévère et cytolyse/insuffisance hépatique = syndrome phalloïdien (amanite phalloïde) : hydratation, silibinine, N-acétylcystéine, transplantation si nécessaire." },
  { id: 'intoxication-tricycliques', nom: 'Intoxication aux antidépresseurs tricycliques', discipline: 'Toxicologie', chapter: 'v-48-cardiotoxiques',
    cles: ['ingestion volontaire', 'coma', 'convulsions', 'tachycardie', 'mydriase', 'hypotension', 'troubles du rythme'],
    orientation: "Coma + convulsions + syndrome anticholinergique + élargissement du QRS = intoxication aux antidépresseurs tricycliques : bicarbonate de sodium molaire (effet stabilisant de membrane)." },
  { id: 'intoxication-betabloquants', nom: 'Intoxication aux bêta-bloquants', discipline: 'Toxicologie', chapter: 'v-48-cardiotoxiques',
    cles: ['ingestion volontaire', 'bradycardie', 'hypotension', 'troubles de conscience', 'troubles du rythme', 'hypoglycémie'],
    orientation: "Bradycardie + hypotension réfractaire ± hypoglycémie et bronchospasme = intoxication aux bêta-bloquants : atropine, glucagon, remplissage." },
  { id: 'intoxication-inhibiteurs-calciques', nom: 'Intoxication aux inhibiteurs calciques', discipline: 'Toxicologie', chapter: 'v-48-cardiotoxiques',
    cles: ['ingestion volontaire', 'hypotension', 'bradycardie', 'troubles du rythme', 'hyperglycémie', 'coma'],
    orientation: "Hypotension profonde + troubles conductifs + hyperglycémie = intoxication aux inhibiteurs calciques : sels de calcium, insulinothérapie euglycémique, catécholamines." },
  { id: 'intoxication-neuroleptiques', nom: 'Intoxication aux neuroleptiques', discipline: 'Toxicologie', chapter: 'v-46-toxicologie-psychotropes',
    cles: ['ingestion volontaire', 'troubles de conscience', 'hyperthermie', 'rigidité', 'tachycardie', 'sueurs', 'troubles du rythme'],
    orientation: "Sédation + syndrome extrapyramidal ± hyperthermie avec rigidité (syndrome malin) = intoxication aux neuroleptiques : arrêt du toxique, refroidissement, dantrolène si syndrome malin." },
];
